spring.application.name=onboarding-assistant

# Ollama chat model
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2

# Ollama embedding model
spring.ai.ollama.embedding.options.model=nomic-embed-text

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/onboarding
spring.datasource.username=onboarding
spring.datasource.password=onboarding

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true


spring.security.oauth2.client.registration.google.client-id=885458717664-4snehm2hgsq8ndck91orqp9qure35ieb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email