spring.application.name=onboarding-assistant

# Ollama chat model
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2

# Ollama embedding model
spring.ai.ollama.embedding.options.model=nomic-embed-text

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/onboarding
spring.datasource.username=onboarding
spring.datasource.password=onboarding

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true


spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false